// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicReportAPI.Migrations
{
    [DbContext(typeof(DynamicReportContext))]
    [Migration("20230309131828_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.MasterInformation", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TaxId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrganizationId");

                    b.ToTable("MasterInformation");

                    b.HasData(
                        new
                        {
                            OrganizationId = new Guid("824e3249-afb0-475b-845e-519a0003b925"),
                            CreatedBy = "John",
                            CreatedOn = new DateTime(2023, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizationName = "Org 1",
                            PrimaryContact = "john@ahaapps.com",
                            TaxId = new Guid("fab10ffb-dc8f-45cd-8421-a207e9c33f9f")
                        },
                        new
                        {
                            OrganizationId = new Guid("8956e747-e94c-4acb-ae12-0528061663d6"),
                            CreatedBy = "Jerry",
                            CreatedOn = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizationName = "Org 2",
                            PrimaryContact = "catherine@ahaapps.com",
                            TaxId = new Guid("f4539220-8b81-41f1-8699-d49b34b1061a")
                        },
                        new
                        {
                            OrganizationId = new Guid("0e75d353-fb97-4da8-982d-eb5818558f0b"),
                            CreatedBy = "Rick",
                            CreatedOn = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizationName = "Org 3",
                            PrimaryContact = "frances@ahaapps.com",
                            TaxId = new Guid("1a70a0d5-ccc8-4602-bbf0-e521f73c98fc")
                        });
                });

            modelBuilder.Entity("DAL.Models.ReportingData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("ReportingData");

                    b.HasData(
                        new
                        {
                            Id = new Guid("655b6f4f-3a86-41bf-a45a-2160ab4e2a35"),
                            Answer = "Assured Partners of CA Insurance Services, LLC dba: Wateridge Insurance Services",
                            OrganizationId = new Guid("824e3249-afb0-475b-845e-519a0003b925"),
                            Question = "Agency Name"
                        },
                        new
                        {
                            Id = new Guid("fb9f1b9b-9b77-4166-9654-f99cdac4672f"),
                            Answer = "Westchester Surplus Lines Ins Co",
                            OrganizationId = new Guid("8956e747-e94c-4acb-ae12-0528061663d6"),
                            Question = "Insurance Carrier(s)"
                        },
                        new
                        {
                            Id = new Guid("75fde238-8ea8-41f1-b773-27404c6ae417"),
                            Answer = "Wateridge Insurance Services",
                            OrganizationId = new Guid("8956e747-e94c-4acb-ae12-0528061663d6"),
                            Question = "Agency Name"
                        },
                        new
                        {
                            Id = new Guid("bd94fdac-0871-4d5d-8e53-979cb43f7087"),
                            Answer = "Middlesex Ins Company",
                            OrganizationId = new Guid("0e75d353-fb97-4da8-982d-eb5818558f0b"),
                            Question = "Insurance Carrier(s)"
                        },
                        new
                        {
                            Id = new Guid("f5c73b1b-cefe-4c9a-a9cc-3da27695115d"),
                            Answer = "(858)200-9999",
                            OrganizationId = new Guid("824e3249-afb0-475b-845e-519a0003b925"),
                            Question = "Fax Number"
                        });
                });

            modelBuilder.Entity("DAL.Models.ReportingData", b =>
                {
                    b.HasOne("DAL.Models.MasterInformation", "MasterInformation")
                        .WithMany("ReportingData")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterInformation");
                });

            modelBuilder.Entity("DAL.Models.MasterInformation", b =>
                {
                    b.Navigation("ReportingData");
                });
#pragma warning restore 612, 618
        }
    }
}
